version: '3.6'
services:
  sam_app:
    build: .
    command: ["$PWD"]
    ports:
      - "3001:3001"
    volumes:
      - ~/.aws/:/root/.aws:ro
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock