AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Case-AskJeeves

  Returns excerpts from Benefits documents based on the given search term.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    Name: case-askjeeves
    EndpointConfiguration: REGIONAL
  Function:
    Runtime: nodejs12.x
    Timeout: 10
    Tags:
      Application: bots
    Environment:
      Variables:
        companyId: '{{resolve:ssm:/Basecamp/CompanyID:1}}'

Resources:
  AskJeevesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: case-askjeeves
      CodeUri: ./
      Handler: app.handler
      Description: Returns GIF based on given search term
      Events:
        AskJeeves:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: post
  AskJeevesFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - AskJeevesFunction
    Properties:
      LogGroupName: !Sub /aws/lambda/${AskJeevesFunction}
      RetentionInDays: 30

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AskJeevesApi:
    Description: 'API Gateway endpoint URL for Prod stage for AskJeeves function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
  AskJeevesFunction:
    Description: 'AskJeeves Lambda Function ARN'
    Value: !GetAtt AskJeevesFunction.Arn
  AskJeevesFunctionIamRole:
    Description: 'Implicit IAM Role created for AskJeeves function'
    Value: !GetAtt AskJeevesFunctionRole.Arn
